apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  kafka-bootstrap-servers: "kafka:9092"
  kafka-topic: "notifications"
  kafka-group-id: "notification-service"
  email-provider-type: "smtp"
  email-provider-host: "smtp.gmail.com"
  email-provider-port: "587"
